import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule} from '@angular/forms';
import { HttpClientModule} from '@angular/common/http';

import { AppComponent } from '@src/app/app.component';
import { NavComponent } from '@src/app/nav/nav.component';
import { ProductComponent } from '@src/app/product/product.component';
import { CategoryComponent } from '@src/app/category/category.component';
import { ProductFilterPipe } from '@src/app/product/product-filter.pipe';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';



@NgModule({
  declarations: [
    AppComponent,
    NavComponent,
    ProductComponent,
    CategoryComponent,
    ProductFilterPipe,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
